# AWS Provider
aws:
  provider_version: "~> 3.10.0"

  # Backend configuration
  backend_bucket: "[BACKEND BUCKET]"
  backend_lock:   "[TABLE NAME]"

  # Common configuration
  default_region: "[YOUR_REGION]"

# GCP Provider
gcp:
  provider_version: "~> 3.43.0"
  project: "[PROJECT NAME]"

  backend_bucket: "[BUCKET NAME]"

  # Common configuration
  default_region: "[YOUR_REGION]"
  default_zone:   "[YOUR_ZONE]"

# Azure Provider
azure:
  provider_version: "~> 2.32.0"

  default_tenant_id: "[TENANT ID]"
  default_subscription_id: "[SUBSCRIPYION ID]"
  default_rgname: "[RESOURCE GROUP NAME]"
  default_region: "[REGION]"

  backend_rgname:        "[RESOURCE GROUP NAME]"
  backend_acctname:      "[STORAGE ACCOUNT NAME]"
  backend_containername: "[STORAGE CONTAINER NAME]"
