# AWS Provider
aws:
  provider_version: "~> 3.10.0"

  # Backend configuration
  backend_bucket: "[BACKEND BUCKET]"
  backend_lock: "[TABLE NAME]"

  # Common configuration
  default_region: ap-northeast-1

# GCP Provider
gcp:
  provider_version: "~> 3.43.0"
  project: "[PROJECT NAME]"

  backend_bucket: "[BUCKET NAME]"

  # Common configuration
  default_region: asia-northeast1
  default_zone:   asia-northeast1-a

# Azure Provider
azure:
  provider_version: "~> 2.32.0"
  default_tenant_id: "[TENANT ID]"
  default_subscription_id: "[SUBSCRIPYION ID]"
  default_rgname: "[RESOURCE GROUP NAME]"
  default_region: "[REGION]"
  backend_rgname: "[RESOURCE GROUP NAME]"
  backend_acctname: "[STORAGE ACCOUNT NAME]"
  backend_containername: "[STORAGE CONTAINER NAME]"
